### ISSUE TITLE
Parsing protocol fails with "java.lang.IllegalStateException: Record[.ErrorRequest]: must have at least one field."

### ISSUE THREAD

**Issue by jangalinski** [toolisticon/avro-kotlin#23]
### Steps to reproduce

When running this code: `AvroKotlin.parseProtocol("org.apache.avro/protocol/simple.avpr")` we get

```
java.lang.IllegalStateException: Record[.ErrorRequest]: must have at least one field.

	at io.toolisticon.avro.kotlin.model.RecordType.<init>(RecordType.kt:34)
	at io.toolisticon.avro.kotlin.model.AvroTypesMap$SchemaCatalog$typesMap$1$1$1.invoke-ESoEMeA(AvroTypesMap.kt:119)
	at io.toolisticon.avro.kotlin.model.AvroTypesMap$SchemaCatalog$typesMap$1$1$1.invoke(AvroTypesMap.kt:59)
	at io.toolisticon.avro.kotlin.model.AvroTypesMap$SchemaCatalog.typesMap$lambda$5$lambda$4$lambda$3(AvroTypesMap.kt:59)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at io.toolisticon.avro.kotlin.model.AvroTypesMap$SchemaCatalog.typesMap(AvroTypesMap.kt:59)
	at io.toolisticon.avro.kotlin.model.AvroTypesMap.<init>(AvroTypesMap.kt:64)
	at io.toolisticon.avro.kotlin.model.AvroTypesMap.<init>(AvroTypesMap.kt:69)
	at io.toolisticon.avro.kotlin.model.wrapper.AvroProtocol$types$2.invoke(AvroProtocol.kt:174)
	at io.toolisticon.avro.kotlin.model.wrapper.AvroProtocol$types$2.invoke(AvroProtocol.kt:173)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.toolisticon.avro.kotlin.model.wrapper.AvroProtocol.getTypes(AvroProtocol.kt:173)
	at io.toolisticon.avro.kotlin.model.wrapper.AvroProtocolTest.parse simple_avpr(AvroProtocolTest.kt:12)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

although the protocol can correctly be parsed by the apache avro parser.

### Expected behaviour

Error types are correctly supported when parsed in protocol messages.

**Comment by jangalinski** [comment]
Analysis: this happens when we define a protocol message tht is one-way and does not have a request parameter. 

```json
 "ack": {
      "doc": "Send a one way message",
      "request": [],
      "response": "null",
      "one-way": true,
      "javaAnnotation": "org.apache.avro.TestAnnotation"
    }
```

basically, this represents a function:

```kotlin
/**
 * Send a one way message
 */ 
@org.apache.avro.TestAnnotation
fun ack() : Unit
```
